### ISSUE TITLE
Slow due to TVGids.nl

### ISSUE THREAD

**Issue by alex341** [tvgrabbers/DataTree#4]
Hi Hika,
I have been using your software for quite some time now, but I run into issues...
I run the software on my Synology NAS and now and then, after an OS update, a DSM update, some package updates, the software stops running. Would be nice to get a warning, but Synology does not provide a working option for that and since your software stops running, I cannot ask you to make a fix.

Another issue is something you can change. After the software stops working, I rerun the install procedures and everything starts working again. However, the entire database, with 2 weeks worth of TV programs needs to be filled. This takes over 30 hours!! It seems that TVGids.nl is slowing thing down. But the entire process has to run before data is written to the data file. Now I do not have data in my datafile and therefor my TVMosaic software does not have a schedule to find his planned recordings.

Is it possible to change that? To write the data to the datafile as soon as it is retrieved? Or to skip a source if it takes to long to respond?

Hope you can solve this one...

Kind regards,

Alex

PS I think I remember you being Dutch, but I do not know for sure. If so, you are welcom to anwser in Dutch!

**Comment by hikavdh** [comment]
A few things. 
First this issue belongs with tvgrabpyAPI.
I know there are issues with Synology, They are related to user and rights management. I cannot do anything about that. But this is very probable the reason for your problem. Try before you rerun the install to first salvage the directory with all files. This is .xmltv in the home directory of the user running it. Check if they are still correctly owned. If this directory has disappeared, try regularly backing it up. Most important is the file `program_cache.db` and its on every run created backup. This is the database you are looking for.
If you want to shorten the timeout on failures, try playing with the [global_timeout](https://github.com/tvgrabbers/tvgrabpyAPI/wiki/configuration#global_timeout) parameter.

**Comment by alex341** [comment]
I chmod 777 the files and got it working. Not only working but super fast. Although I cannot grasp the fact that ownership and rights have an impact on the speed, it apparantly does. 
Seems to be working again now! Tnx for the quick response!
